### PR TITLE
Contribution label change

### LINKED ISSUE #39: Modifier l'intitulé de la ligne "Contribution au développement de l'apprentissage"
Nouvel intitulé : "Contribution supplémentaire à l'apprentissage"

### PR DESCRIPTION
**Pull request by laem**
Fixes #39  and contrib. label typos

### CODE REVIEW

**Comment by MattiSG** [comment]
GTM

**Comment by MattiSG** [comment]
Good commit splits.

Avoid abbreviations. Domain terms should always be used in full to avoid being opaque or ambiguous.

Try to be more explicit in PR titles: saying something “changed” does not say anything on how it changed, and one expects a PR to change something.
For example, here: “Improve some cotisations labels” could have been clearer.

**Comment by MattiSG** [comment]
Please wait before merging, we'll do it together to see how to compile and distribute.

**Comment by laem** [comment]
I'd also prefer "cotisation" over the misleading "contribution" on git but it doesn't exist :-)

**Comment by MattiSG** [comment]
> it doesn't exist

What doesn't exist?

**Comment by laem** [comment]
> What doesn't exist?

`cotisation` in english

**Comment by MattiSG** [comment]
That's a [domain](https://en.wikipedia.org/wiki/Domain-driven_design) name, it should be kept in French  :)  ([reference on Domain-Driven Design](http://blog.infosaurus.fr/public/docs/DDDViteFait.pdf))

You can find the reasoning [here](https://github.com/sgmap/paie-api/blob/master/CONTRIBUTING.md#language). We'll discuss it this afternoon, and write the results (in French) in this CONTRIBUTING file.

**Pull request merged**
